DROP  DATABASE IF EXISTS test;
CREATE DATABASE IF NOT EXISTS test;
use test;

CREATE TABLE IF NOT EXISTS estudiantes (
	id INT NOT NULL AUTO_INCREMENT,
	nombre varchar(100) NOT NULL,
	comidaPreferida varchar(100) NULL,
	nacimiento DATE NOT NULL,
	CONSTRAINT estudiantes_PK PRIMARY KEY (id)
);

INSERT INTO ESTUDIANTES VALUES
(1, "JUAN PEDRO", "EMPANADA", "1973/04/01"),
(2, "CAROLINA JIMANEZ", "ÑOQUIS", "1976/03/01"),
(3, "JUAN SANCHEZ", "ARROZ", "1986/12/03"),
(4, "FACUNDO ABADI", "PIZZA", "2002/04/15"),
(5, "MARIA JUANA", "HAMBURGUESA", "1996/03/25");

CREATE TABLE IF NOT EXISTS test.profesor (
	id.p INT NOT NULL AUTO_INCREMENT,
	nombre varchar(100) NOT NULL,
	comidafavorita varchar(100) NULL,
	materia varchar(100) NULL,
	fechanacimiento DATE NOT NULL,
CONSTRAINT profesor_PK PRIMARY KEY (id)
);
INSERT INTO PROFESOR VALUES
(20, "DANILO TORRES", "SUSHI","LENGUA", "1993/04/01"),
(21, "MARIA DAUJAN", "HUEVO","MATEMATICAS", "1992/04/01"),
(22, "PATRICIA MAGUIRE", "HELADO","GEOGRAFIA", "1973/04/01"),
(23, "MARIANO DANTE", "GUISO","CIVICA", "1990/04/01"),
(24, "JUAN TORRES", "SUSHI","INGLES", "1988/04/01"),
(25, "YAMILED SUAREZ", "TACOS","JAPONES", "1989/04/01");
